name: create a comment on a newly created issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      # - name: Create comment using API
      #   uses: peter-evans/create-or-update-comment@v3
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: |
      #       This is a multi-line test comment
      #       - With GitHub **Markdown** :sparkles:
      #       - Created by [create-or-update-comment][1]

      #       [1]: https://github.com/peter-evans/create-or-update-comment
      #     reactions: "+1"

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
          gh api -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"body": "Comment created by workflow on commit SHA ${{ github.sha }}" }' \
            "/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
